const {chromium}=require('C:/Users/raozhengfei/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
const fs=require('fs');
const assert=require('assert/strict');
const {pathToFileURL}=require('url');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'gripper-preview.html')).href);
 await page.waitForFunction(()=>window.gripperPreview);
 assert.equal((await page.evaluate(()=>window.gripperPreview.getState())).parts,43);
 await page.screenshot({path:path.join(__dirname,'preview-32-exploded.png'),fullPage:true});
 console.log('32 initial',await page.evaluate(()=>window.gripperPreview.getState()));
 await page.locator('#explode').fill('0');
 await page.locator('[data-model="12"]').click();
 await page.locator('#explode').fill('80');
 await page.screenshot({path:path.join(__dirname,'preview-12-exploded.png')});
 console.log('12 exploded',await page.evaluate(()=>window.gripperPreview.getState()));
 await page.locator('[data-category="silicone"]').uncheck();
 console.log('silicone hidden',await page.evaluate(()=>window.gripperPreview.getState()));
 await page.locator('[data-category="silicone"]').check();
 await page.locator('#opacity').fill('35');
 await page.locator('[data-view="back"]').click();
 await page.locator('[data-view="iso"]').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#save-image').click();const download=await downloadPromise;assert.equal((await download.failure()),null);assert.equal(fs.readFileSync(await download.path()).subarray(1,4).toString(),'PNG');
 await page.setViewportSize({width:360,height:1100});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const apiResult=await page.evaluate(()=>{const api=window.gripperPreview;api.setModel(32);api.setExplode(100);api.setVisibility('silicone',false);api.setView('side');const state=api.getState();let rejected=0;for(const action of [()=>api.setModel(13),()=>api.setExplode(-1),()=>api.setVisibility('missing',true)]){try{action();}catch{rejected++;}}return {state,rejected};});
 assert.equal(apiResult.state.parts,43);assert.equal(apiResult.state.visible,42);assert.equal(apiResult.state.explode,100);assert.equal(apiResult.rejected,3);
 console.log('errors',errors);
 await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
